matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx

language: cpp

before_install:
  - MY_LOCATION=`pwd`
# SDL1.2 specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install sdl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y libsdl1.2-dev; fi
# End of SDL1.2 specific part
#-----------------------
# SystemC specific part
#-----------------------
  - wget http://accellera.org/images/downloads/standards/systemc/systemc-2.3.1.tgz
  - tar -zxvf systemc-2.3.1.tgz
  - SYSTEMC_INSTALL=${MY_LOCATION}/systemc_install
  - export SYSTEMC_INSTALL
  - mkdir $SYSTEMC_INSTALL
  - cd systemc-2.3.1
  - mkdir objdir
  - cd objdir/
  - ../configure --prefix=$SYSTEMC_INSTALL
  - make -j
  - make install
# End of SystemC specific part
#-----------------------
  - cd $MY_LOCATION
  - chmod a+x sources/quicky_tools/bin/*
  - QUICKY_REPOSITORY=`pwd`/sources
  - export QUICKY_REPOSITORY
  - cd $QUICKY_REPOSITORY/quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
# SystemC part
  - LD_LIBRARY_PATH=$SYSTEMC_INSTALL/`ls -1 ${SYSTEMC_INSTALL}/ | grep lib`:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH

script:
# Build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . build_cmake.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . build.sh; fi
#EOF
